debian/tmp/etc
debian/tmp/usr/bin

debian/tmp/usr/lib/chromium/chromium
debian/tmp/usr/lib/chromium/chrome-sandbox
debian/tmp/usr/lib/chromium/*.pak
debian/tmp/usr/lib/chromium/resources/extension/demo/library.js
debian/tmp/usr/lib/chromium/content_resources.pak
debian/tmp/usr/lib/chromium/locales/*
debian/tmp/usr/lib/chromium/remoting_locales
debian/tmp/usr/lib/chromium/lib*
debian/tmp/usr/lib/chromium/pseudo_locales/fake-bidi.pak
debian/tmp/usr/lib/chromium/icudtl.dat

debian/chromium.desktop usr/share/applications

debian/chromium.xml usr/share/gnome-control-center/default-apps

debian/initial_bookmarks.html etc/chromium
debian/master_preferences etc/chromium

debian/presubj usr/share/bug/chromium
