out/Release/chromium usr/lib/chromium
out/Release/chrome-sandbox usr/lib/chromium

out/Release/lib* usr/lib/chromium
out/Release/*.pak usr/lib/chromium
out/Release/icudtl.dat usr/lib/chromium

out/Release/resources/*.pak usr/lib/chromium/locales

debian/presubj usr/share/bug/chromium

debian/initial_bookmarks.html usr/lib/chromium
debian/master_preferences usr/lib/chromium

debian/chromium.xml usr/share/gnome-control-center/default-apps
