debian/tmp/etc
debian/tmp/usr/bin
debian/tmp/usr/lib/chromium-browser/chrom*
debian/tmp/usr/lib/chromium-browser/xdg-settings
debian/tmp/usr/lib/chromium-browser/resources/bookmark_manager
debian/tmp/usr/lib/chromium-browser/resources/net_internals
#debian/tmp/usr/lib/chromium-browser/icudt38l.dat
debian/tmp/usr/lib/chromium-browser/locales/*
debian/chromium-browser.desktop usr/share/applications
debian/chromium-browser.xml usr/share/gnome-control-center/default-apps
master_preferences etc/chromium-browser
