#!/bin/bash -eu

_debian_dir=$(dirname $(dirname $(readlink -f $0)))
_root_dir=$(dirname $_debian_dir)
_domsubcache="$_debian_dir/domsubcache.tar.gz"
_ungoogled_chromium="$_debian_dir/ungoogled-upstream/ungoogled-chromium"

if [ -e $_domsubcache ]; then 
	python3 -B $_ungoogled_chromium/utils/domain_substitution.py revert -c $_domsubcache $_root_dir
else
	echo 'Domain substitution cache does not exist. Aborting.'
fi
