#!/bin/bash -eu

DEBIAN=$(pwd)/debian
PATCHES=$DEBIAN/patches
SCRIPTS=$DEBIAN/scripts
UNGOOGLED_CHROMIUM=$DEBIAN/ungoogled-upstream/ungoogled-chromium
UTILS=$UNGOOGLED_CHROMIUM/utils

setup_source()
{
    local CACHE=../download_cache
    local ROOT=$1
    test -d $CACHE || mkdir $CACHE
    test -d $ROOT || mkdir $ROOT
    python3 -B $UTILS/downloads.py retrieve -i $UNGOOGLED_CHROMIUM/downloads.ini -c $CACHE
    python3 -B $UTILS/downloads.py unpack -i $UNGOOGLED_CHROMIUM/downloads.ini -c $CACHE $ROOT
    python3 -B $UTILS/prune_binaries.py $ROOT $UNGOOGLED_CHROMIUM/pruning.list
    $SCRIPTS/remove_copyright_excluded $ROOT
    (cd $ROOT && $SCRIPTS/check-upstream)
}

translate_rules()
{
sed -e '/^--- a\/.*\/spellcheck_hunspell_dictionary\.cc$/,/^--- a\//{//!d}' \
    -e '/^--- a\/.*\/translate_url_fetcher\.cc$/,/^--- a\//{//!d}' \
    -e '/^--- a\/.*\/translate_util\.cc$/,/^--- a\//{//!d}' \
    -e '/spellcheck_hunspell_dictionary/{g;d}' \
    -e '/translate/{g;d}' \
    -i $PATCHES/core/iridium-browser/all-add-trk-prefixes-to-possibly-evil-connections.patch

if [ -z "$(grep 'google translate domain substitutions' $DEBIAN/rules)" ]; then
    sed -e '/debian\/scripts\/apply_domainsubstitution/a\
	# revert google translate domain substitutions\
	\./debian/scripts/translate_domsubs revert'\
\
        -e '/^override_dh_prep:/a\
	# re-apply google translate domain substitutions\
	\./debian/scripts/translate_domsubs apply'\
\
        -i $DEBIAN/rules
fi
}

case "$1" in

debian)
    python3 -B $UTILS/patches.py merge -p $DEBIAN/patches $UNGOOGLED_CHROMIUM/patches
    $SCRIPTS/generate_changelog
    sed -i "/^Maintainer:/cMaintainer: $(cat debian/uploader.txt)" $DEBIAN/control
    ;;

local-src)
    setup_source .
    ;;

orig-source)
    VERSION=$(cat $UNGOOGLED_CHROMIUM/chromium_version.txt)
    EXTRACT=chromium-$VERSION
    test ! -e $EXTRACT || rm -rf $EXTRACT
    setup_source $EXTRACT
    tar -c $EXTRACT | xz -9 > ../ungoogled-chromium_$VERSION.orig.tar.xz
    rm -rf $EXTRACT
    ;;

translate-enable)
    translate_rules
    ;;

esac
